steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/spa-repo/backend:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/spa-repo/backend:$SHORT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'spa-backend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/spa-repo/backend:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=DB_HOST=35.254.104.173,DB_PORT=5432,DB_NAME=spa_db,DB_USER=spa_user,DB_PASSWORD=SpaSecure2024!,JWT_SECRET=spa_jwt_secret_key_production_2024,GOOGLE_CLOUD_PROJECT=d-30-488909,BUCKET_THERAPIST_PHOTOS=spa-tcc-therapist-photos-d30,BUCKET_PAYMENT_PROOFS=spa-tcc-payment-proofs-d30'
      - '--max-instances=3'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/spa-repo/backend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY